### ISSUE TITLE
Spigot - 1.12.2- Snapshot - Error Enabling SuperbVote

### ISSUE THREAD

**Issue by Chrustee96** [astei/SuperbVote#53]
Keep having the following error every time i boot my server now. I don't understand where to begin. Please help! 

________________________________________
**[11:15:53] [Server thread/INFO]: [SuperbVote] Enabling SuperbVote v0.4.1
[11:15:53] [Server thread/ERROR]: Error occurred while enabling SuperbVote v0.4.1 (Is it up to date?)
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $**
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224) ~[spigot.jar:git-Spigot-2086bb0-8cc5a7e]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[spigot.jar:git-Spigot-2086bb0-8cc5a7e]
	at com.google.gson.Gson.fromJson(Gson.java:825) ~[spigot.jar:git-Spigot-2086bb0-8cc5a7e]
	at io.minimum.minecraft.superbvote.storage.JsonVoteStorage.<init>(JsonVoteStorage.java:40) ~[?:?]
	at io.minimum.minecraft.superbvote.configuration.SuperbVoteConfiguration.initializeVoteStorage(SuperbVoteConfiguration.java:160) ~[?:?]
	at io.minimum.minecraft.superbvote.SuperbVote.onEnable(SuperbVote.java:44) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot.jar:git-Spigot-2086bb0-8cc5a7e]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot.jar:git-Spigot-2086bb0-8cc5a7e]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot.jar:git-Spigot-2086bb0-8cc5a7e]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [spigot.jar:git-Spigot-2086bb0-8cc5a7e]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [spigot.jar:git-Spigot-2086bb0-8cc5a7e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot.jar:git-Spigot-2086bb0-8cc5a7e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot.jar:git-Spigot-2086bb0-8cc5a7e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot.jar:git-Spigot-2086bb0-8cc5a7e]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot.jar:git-Spigot-2086bb0-8cc5a7e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot.jar:git-Spigot-2086bb0-8cc5a7e]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385) ~[spigot.jar:git-Spigot-2086bb0-8cc5a7e]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:213) ~[spigot.jar:git-Spigot-2086bb0-8cc5a7e]
	... 16 more

**Comment by sandor111** [comment]
Try using the 0.5.1 version.

**Comment by sandor111** [comment]
Try using version 0.5.1

**Comment by astei** [comment]
Inactive for a long time, closing.
