### ISSUE TITLE
java.lang.RuntimeException: Exception whilst initializing vote storage

### ISSUE THREAD

**Issue by marvinej** [astei/SuperbVote#61]
[12:11:03 INFO]: This server is running CraftBukkit version git-Spigot-f823ac5-020b495 (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)

[12:07:16 INFO]: [SuperbVote] Enabling SuperbVote v0.5.3
[12:07:16 ERROR]: Error occurred while enabling SuperbVote v0.5.3 (Is it up to date?)
java.lang.RuntimeException: Exception whilst initializing vote storage
        at io.minimum.minecraft.superbvote.SuperbVote.onEnable(SuperbVote.java:54) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot.jar:git-Spigot-f823ac5-020b495]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) [spigot.jar:git-Spigot-f823ac5-020b495]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot.jar:git-Spigot-f823ac5-020b495]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:431) [spigot.jar:git-Spigot-f823ac5-020b495]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:345) [spigot.jar:git-Spigot-f823ac5-020b495]
        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:584) [spigot.jar:git-Spigot-f823ac5-020b495]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:546) [spigot.jar:git-Spigot-f823ac5-020b495]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:424) [spigot.jar:git-Spigot-f823ac5-020b495]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294) [spigot.jar:git-Spigot-f823ac5-020b495]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:702) [spigot.jar:git-Spigot-f823ac5-020b495]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.nio.file.AccessDeniedException: plugins\SuperbVote\votes.json
        at sun.nio.fs.WindowsException.translateToIOException(Unknown Source) ~[?:1.8.0_181]
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source) ~[?:1.8.0_181]
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source) ~[?:1.8.0_181]
        at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(Unknown Source) ~[?:1.8.0_181]
        at java.nio.file.Files.newByteChannel(Unknown Source) ~[?:1.8.0_181]
        at java.nio.file.Files.newByteChannel(Unknown Source) ~[?:1.8.0_181]
        at java.nio.file.spi.FileSystemProvider.newInputStream(Unknown Source) ~[?:1.8.0_181]
        at java.nio.file.Files.newInputStream(Unknown Source) ~[?:1.8.0_181]
        at java.nio.file.Files.newBufferedReader(Unknown Source) ~[?:1.8.0_181]
        at java.nio.file.Files.newBufferedReader(Unknown Source) ~[?:1.8.0_181]
        at io.minimum.minecraft.superbvote.storage.JsonVoteStorage.<init>(JsonVoteStorage.java:41) ~[?:?]
        at io.minimum.minecraft.superbvote.configuration.SuperbVoteConfiguration.initializeVoteStorage(SuperbVoteConfiguration.java:176) ~[?:?]
        at io.minimum.minecraft.superbvote.SuperbVote.onEnable(SuperbVote.java:52) ~[?:?]
        ... 11 more

**Comment by astei** [comment]
Please check your file permissions. Not a SuperbVote issue.
