### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by iamharak** [astei/SuperbVote#62]
An error is generated after the table has been dropped:
[22:25:07 ERROR]: Could not pass event BlockPlaceEvent to SuperbVote v0.5.3
java.lang.NoSuchFieldError: SKELETON_WALL_SKULL
at io.minimum.minecraft.superbvote.signboard.TopPlayerSignListener.onBlockPlace(TopPlayerSignListener.java:58) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor378.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[tacospigot.jar:git-TacoSpigot-"f8ba67d6"]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[tacospigot.jar:git-TacoSpigot-"f8ba67d6"]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[tacospigot.jar:git-TacoSpigot-"f8ba67d6"]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:527) ~[tacospigot.jar:git-TacoSpigot-"f8ba67d6"]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:512) ~[tacospigot.jar:git-TacoSpigot-"f8ba67d6"]
at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:151) ~[tacospigot.jar:git-TacoSpigot-"f8ba67d6"]
at net.minecraft.server.v1_12_R1.ItemStack.placeItem(ItemStack.java:230) ~[tacospigot.jar:git-TacoSpigot-"f8ba67d6"]
at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:513) ~[tacospigot.jar:git-TacoSpigot-"f8ba67d6"]
at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:993) ~[tacospigot.jar:git-TacoSpigot-"f8ba67d6"]
at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[tacospigot.jar:git-TacoSpigot-"f8ba67d6"]
at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[tacospigot.jar:git-TacoSpigot-"f8ba67d6"]
at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[tacospigot.jar:git-TacoSpigot-"f8ba67d6"]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [tacospigot.jar:git-TacoSpigot-"f8ba67d6"]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [tacospigot.jar:git-TacoSpigot-"f8ba67d6"]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) [tacospigot.jar:git-TacoSpigot-"f8ba67d6"]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [tacospigot.jar:git-TacoSpigot-"f8ba67d6"]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [tacospigot.jar:git-TacoSpigot-"f8ba67d6"]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]

**Comment by iamharak** [comment]
*Not just after laying down a sign. Unfortunately, I do not know exactly when.

**Comment by astei** [comment]
Use SuperbVote 0.5.2-1.12: https://www.spigotmc.org/resources/superbvote.11626/history
