### ISSUE TITLE
nullpoiinter task#69

### ISSUE THREAD

**Issue by cptriven** [astei/SuperbVote#66]
[01:51:03 WARN]: [SuperbVote] Task #69 for SuperbVote v0.5.2-1.12 generated an exception
java.lang.NullPointerException: null
        at java.lang.String.replace(Unknown Source) ~[?:?]
        at io.minimum.minecraft.superbvote.configuration.message.placeholder.SuperbVotePlaceholderProvider.apply(SuperbVotePlaceholderProvider.java:9) ~[?:?]
        at io.minimum.minecraft.superbvote.configuration.message.MessageBase.replace(MessageBase.java:19) ~[?:?]
        at io.minimum.minecraft.superbvote.configuration.message.PlainStringMessage.getWithOfflinePlayer(PlainStringMessage.java:33) ~[?:?]
        at io.minimum.minecraft.superbvote.signboard.TopPlayerSignUpdater.run(TopPlayerSignUpdater.java:61) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot2.jar:git-Spigot-2cf50f0-2b93d83]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot2.jar:git-Spigot-2cf50f0-2b93d83]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot2.jar:git-Spigot-2cf50f0-2b93d83]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot2.jar:git-Spigot-2cf50f0-2b93d83]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot2.jar:git-Spigot-2cf50f0-2b93d83]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot2.jar:git-Spigot-2cf50f0-2b93d83]
        at java.lang.Thread.run(Unknown Source) [?:?]

config yml
# SuperbVote configuration
# A superb vote plugin made by Tux.
#
# https://github.com/minecrafter/SuperbVote/wiki

# Once you've configured SuperbVote, add it to our official server list, CraftServers.net:
# Official server list: https://www.craftservers.net/

# Database configuration.
storage:
  database: MySQL
  json:
    file: votes.json
  mysql:
    host: 172.0.1:3306
    username: minecraft1012
    password: non of your buissnes
    database: superbvote
    table: votes
    read-only: false

# General vote configuration.
votes:
  # At least this many seconds must pass before allowing another vote (per-service). This will apply per service.
  # Default: 3600 seconds (1 hour)
  cooldown-per-service: 0

  # Whether or not to treat fake votes as real votes
  process-fake-votes: true

# Rewards. This is the main section you will need to edit. Ordering is important.
rewards:
  # Example of matchers. See https://github.com/minecrafter/SuperbVote/wiki/Configuration#if for a full list of available
  # matchers.
  - if:
      permission: superbvote.test
      chance-percentage: 5
      service: SpecialService
    commands:
    - give %player% diamond 4
    - eco give %player% 1000
    player-message: "&aThanks for meeting nearly impossible conditions, you have been rewarded with 4 diamonds and $1000."
    broadcast-message: "&a%player% got really lucky and was rewarded with 4 diamonds and $1000!"
  # A default reward is required. Default rewards are defined by using default: true as a matcher. No other matchers can
  # be used with this matcher and only one such reward can be the default reward.
  - if:
      default: true
    commands:
    - eco give %player% 300
    - give %player% diamond 16
    - give %player% golden_apple 1
    player-message: "&aDanke für deinen Vote! Du erhälst RC 300, 16xDiamanten und einen goldenen Apfel."
    broadcast-message: "&a%player% hat für den Server gevotet und hat etwas tolles erhalten!"

# Whether or not players need to be online to vote. If set, offline player votes are queued for when the player next logs in.
require-online: false

# Broadcast settings:
broadcast:
  # Should we broadcast votes at all?
  enabled: true

  # Should we tell players if they voted?
  message-player: true

  # Should we broadcast queued votes?
  queued: true

# Vote command.
# See http://www.minecraftforum.net/forums/minecraft-discussion/redstone-discussion-and/351959-1-9-json-text-component-for-tellraw-title-books
# and https://www.minecraftjson.com for json text format
vote-command:
  enabled: true
  use-json-text: false
  text: |-
    Vote hier für uns https://minecraft-server.eu/vote/index/2039D

# Vote reminder.
vote-reminder:
  message: "&c Du hast derzeit  &a%votes%&cx für den Server gevotet."
  on-join: true
  repeat: 2000

# Controls the /sv <top/leaderboard> command.
leaderboard:
  # Supported: text, scoreboard
  display: text

  # The text format supports pagination.
  text:
    per-page: 10
    header: "&c&m         &r&b Top Voters &r&c&m         &r"
    entry: "&e%num%. &7%player% (&e%votes%&7 votes)"
    page: "&7(page %page%/%total%)"

  # Control the scoreboard.
  scoreboard:
    title: Top voters
    max: 10

# Control top player signs.
top-player-signs:
  format:
  - "#%num%"
  - ""
  - "%player%"
  - "&l%votes% &rvotes"

**Comment by astei** [comment]
Fixed in SuperbVote 0.5.4, but you won't get it because you're on 1.12 and I don't have the time to maintain 1.12 any more.
