### ISSUE TITLE
Why this error happens?

### ISSUE THREAD

**Issue by OngMong** [astei/SuperbVote#67]
```
Unexpected exception while parsing console command "sv reload"
org.bukkit.command.CommandException: Unhandled exception executing command 'sv' in plugin SuperbVote v0.5.3
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-51c118b]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:139) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-51c118b]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:704) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-51c118b]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchServerCommand(CraftServer.java:689) [spigot-1.13.2.jar:git-Spigot-b0f4c22-51c118b]
	at net.minecraft.server.v1_13_R2.DedicatedServer.handleCommandQueue(DedicatedServer.java:459) [spigot-1.13.2.jar:git-Spigot-b0f4c22-51c118b]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:418) [spigot-1.13.2.jar:git-Spigot-b0f4c22-51c118b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.2.jar:git-Spigot-b0f4c22-51c118b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.2.jar:git-Spigot-b0f4c22-51c118b]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.lang.IllegalArgumentException: Section 'vote-reminder.message' (under ) doesn't contain a valid message section.
	at io.minimum.minecraft.superbvote.configuration.message.VoteMessages.from(VoteMessages.java:23) ~[?:?]
	at io.minimum.minecraft.superbvote.configuration.message.VoteMessages.from(VoteMessages.java:10) ~[?:?]
	at io.minimum.minecraft.superbvote.configuration.SuperbVoteConfiguration.<init>(SuperbVoteConfiguration.java:98) ~[?:?]
	at io.minimum.minecraft.superbvote.SuperbVote.reloadPlugin(SuperbVote.java:118) ~[?:?]
	at io.minimum.minecraft.superbvote.commands.SuperbVoteCommand.onCommand(SuperbVoteCommand.java:201) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-51c118b]
	... 8 more
```

**Comment by astei** [comment]
You removed the vote reminder message. Don't do that. [If you looked at the documentation, it'll tell you how to disable the vote reminder correctly.](https://github.com/astei/SuperbVote/wiki/FAQ#how-do-i-disable-the-vote-reminder)
