### ISSUE TITLE
json-text enabled causing IIlegalStateException

### ISSUE THREAD

**Issue by kxrider85** [astei/SuperbVote#68]
Whenever I enable use-json-text under vote-command, I get the following error:
`> [02:07:47 INFO]: kxrider85 issued server command: /vote
> [02:07:47 WARN]: [SuperbVote] Plugin SuperbVote v0.5.3 generated an exception while executing task 59
java.lang.IllegalStateException: Asynchronous command dispatch!
at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14) ~[spigot.jar:git-Spigot-f09662d-0bf75bb]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:702) ~[spigot.jar:git-Spigot-f09662d-0bf75bb]
at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:655) ~[spigot.jar:git-Spigot-f09662d-0bf75bb]
at io.minimum.minecraft.superbvote.configuration.message.JsonTextMessage.sendAsReminder(JsonTextMessage.java:22) ~[?:?]
at io.minimum.minecraft.superbvote.commands.VoteCommand.lambda$onCommand$0(VoteCommand.java:34) ~[?:?]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot.jar:git-Spigot-f09662d-0bf75bb]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot.jar:git-Spigot-f09662d-0bf75bb]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_202]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_202]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]`

At first I thought it was an issue with my formatting, but even just leaving the text section blank gives the error when I `/vote` as a player.

All of these give the same error:
`vote-command:
  enabled: true
  use-json-text: true
  text: |-
    {}`

`vote-command:
  enabled: true
  use-json-text: true
  text: |-
    `

`vote-command:
  enabled: true
  use-json-text: true
  text: |-
    {"text":"test"}
`

**Comment by astei** [comment]
Fixed in SuperbVote 0.5.4
