### ISSUE TITLE
trouble with network sv

### ISSUE THREAD

**Issue by patchtv** [astei/SuperbVote#72]
I'm using my hub server as the main vote processor, and copy-pasted the plugin and config into all my game servers, disabling the "commands" rewards in those.
when I do /vote, however on any of my game servers i get this:
`[SuperbVote] Plugin SuperbVote v0.5.2-1.12 generated an exception while executing task 290
java.lang.IllegalStateException: Asynchronous command dispatch!
at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[patched_1.13.2.jar:git-Paper-626]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:709) ~[patched_1.13.2.jar:git-Paper-626]
at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:688) ~[patched_1.13.2.jar:git-Paper-626]
at io.minimum.minecraft.superbvote.configuration.message.JsonTextMessage.sendAsReminder(JsonTextMessage.java:22) ~[?:?]
at io.minimum.minecraft.superbvote.commands.VoteCommand.lambda$onCommand$0(VoteCommand.java:34) ~[?:?]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.13.2.jar:git-Paper-626]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.2.jar:git-Paper-626]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.2.jar:git-Paper-626]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212] `

my config:
https://hasteb.in/ajoziyix.pl
do i need to set all my game servers to read-only on the mysql? why would it then error out on the json of /vote?

**Comment by patchtv** [comment]
additionally, this only happened on my 1.13.2 smp server, and my 1.14.2 minigames server. could i have an outdated version of the plugin perhaps?

**Comment by astei** [comment]
Update SuperbVote
