### ISSUE TITLE
Corrupted Database

### ISSUE THREAD

**Issue by SrBedrock** [astei/SuperbVote#76]
I think I corrupted the database after a system crash.
How can I fix it?

```
[00:02:01] [Server thread/INFO]: [SuperbVote] Enabling SuperbVote v0.5.4
[00:02:01] [Server thread/WARN]: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
[00:02:01] [Server thread/WARN]: SLF4J: Defaulting to no-operation (NOP) logger implementation
[00:02:01] [Server thread/WARN]: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[00:02:01] [Server thread/WARN]: Tue Aug 06 00:02:01 EDT 2019 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
[00:02:01] [Server thread/INFO]: [SuperbVote] Migrating database from version 1 to 4, this may take a while...
[00:02:01] [Server thread/ERROR]: [SuperbVote] Unable to initialize database
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Duplicate column name 'last_vote'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_212]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_212]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_212]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[patched_1.14.4.jar:git-Paper-156]
	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[patched_1.14.4.jar:git-Paper-156]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944) ~[patched_1.14.4.jar:git-Paper-156]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978) ~[patched_1.14.4.jar:git-Paper-156]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914) ~[patched_1.14.4.jar:git-Paper-156]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530) ~[patched_1.14.4.jar:git-Paper-156]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683) ~[patched_1.14.4.jar:git-Paper-156]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2491) ~[patched_1.14.4.jar:git-Paper-156]
	at com.mysql.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1552) ~[patched_1.14.4.jar:git-Paper-156]
	at com.mysql.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2607) ~[patched_1.14.4.jar:git-Paper-156]
	at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1480) ~[patched_1.14.4.jar:git-Paper-156]
	at io.minimum.minecraft.superbvote.hikari.pool.ProxyStatement.executeUpdate(ProxyStatement.java:120) ~[?:?]
	at io.minimum.minecraft.superbvote.hikari.pool.HikariProxyStatement.executeUpdate(HikariProxyStatement.java) ~[?:?]
	at io.minimum.minecraft.superbvote.storage.MysqlVoteStorage.initialize(MysqlVoteStorage.java:57) ~[?:?]
	at io.minimum.minecraft.superbvote.configuration.SuperbVoteConfiguration.initializeVoteStorage(SuperbVoteConfiguration.java:194) ~[?:?]
	at io.minimum.minecraft.superbvote.SuperbVote.onEnable(SuperbVote.java:52) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.14.4.jar:git-Paper-156]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.14.4.jar:git-Paper-156]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.14.4.jar:git-Paper-156]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467) ~[patched_1.14.4.jar:git-Paper-156]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381) ~[patched_1.14.4.jar:git-Paper-156]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:474) ~[patched_1.14.4.jar:git-Paper-156]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:282) ~[patched_1.14.4.jar:git-Paper-156]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:869) ~[patched_1.14.4.jar:git-Paper-156]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
[00:02:01] [Server thread/INFO]: [SuperbVote] Using clip's PlaceholderAPI to provide extra placeholders.

**Comment by TheVirusGut** [comment]
Hey, did you ever find a fix for this? lol.
