### ISSUE TITLE
MySQLSyntaxErrorException: Duplicate column name 'last_vote'

### ISSUE THREAD

**Issue by viveleroi** [astei/SuperbVote#92]
I've just installed the plugin for the first time.

Plugin seems to be trying to update the database scheme every server start, but it should have already been a fresh install (no previous schemas/versions etc).

```
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Duplicate column name 'last_vote'
	at jdk.internal.reflect.GeneratedConstructorAccessor73.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[patched_1.15.2.jar:git-Paper-264]
	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[patched_1.15.2.jar:git-Paper-264]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944) ~[patched_1.15.2.jar:git-Paper-264]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3933) ~[patched_1.15.2.jar:git-Paper-264]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869) ~[patched_1.15.2.jar:git-Paper-264]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524) ~[patched_1.15.2.jar:git-Paper-264]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2675) ~[patched_1.15.2.jar:git-Paper-264]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465) ~[patched_1.15.2.jar:git-Paper-264]
	at com.mysql.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1536) ~[patched_1.15.2.jar:git-Paper-264]
	at com.mysql.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2585) ~[patched_1.15.2.jar:git-Paper-264]
	at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1464) ~[patched_1.15.2.jar:git-Paper-264]
	at io.minimum.minecraft.superbvote.hikari.pool.ProxyStatement.executeUpdate(ProxyStatement.java:120) ~[?:?]
	at io.minimum.minecraft.superbvote.hikari.pool.HikariProxyStatement.executeUpdate(HikariProxyStatement.java) ~[?:?]
	at io.minimum.minecraft.superbvote.storage.MysqlVoteStorage.initialize(MysqlVoteStorage.java:57) ~[?:?]
	at io.minimum.minecraft.superbvote.configuration.SuperbVoteConfiguration.initializeVoteStorage(SuperbVoteConfiguration.java:194) ~[?:?]
	at io.minimum.minecraft.superbvote.SuperbVote.onEnable(SuperbVote.java:52) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-264]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:364) ~[patched_1.15.2.jar:git-Paper-264]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-264]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:472) ~[patched_1.15.2.jar:git-Paper-264]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:386) ~[patched_1.15.2.jar:git-Paper-264]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488) ~[patched_1.15.2.jar:git-Paper-264]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-264]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:896) ~[patched_1.15.2.jar:git-Paper-264]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by astei** [comment]
This is likely because you're trying to do a multi-server setup. Put this into `plugins/SuperbVote/db_version.yml`:

```
db_version: 4
```

And reboot. That should take care of the issue.

I know this needs to be handled better, but my hands are constantly full with other things.

**Comment by astei** [comment]
Tracking this in #103.
